### ISSUE TITLE
关于文档描述和代码不一致的疑问。

### ISSUE THREAD

**Issue by gillian911911** [iyuge2/M-SENA-Backend#2]
todo

**Comment by FlameSky-S** [comment]
您好，当前文档是基于之前v_1.0版本的，没有进行更新。对于最新master分支，直接执行`python main.py` 即可。

**Comment by gillian911911** [comment]
> 您好，当前文档是基于之前v_1.0版本的，没有进行更新。对于最新master分支，直接执行`python main.py` 即可。

感谢您在百忙之中抽出时间回复，我按照您的方案，执行 `python main.py`

报了以下异常，您方便指点一下吗？

```python
SENA_run is not loaded due to missing dependencies. This is ok if you are not using M-SENA.
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from app import app
  File "/home/github.com/M-SENA-Backend/app/__init__.py", line 24, in <module>
    from .analysis import *
  File "/home/github.com/M-SENA-Backend/app/analysis.py", line 17, in <module>
    from MMSA import DEMO_run
ImportError: cannot import name 'DEMO_run' from 'MMSA' (/root/anaconda3/lib/python3.8/site-packages/MMSA/__init__.py)
```

**Comment by FlameSky-S** [comment]
请检查python环境是否安装了scipy和mysql-connector-python。如未安装，使用 “pip install mysql-connector-python scipy” 来安装。

**Comment by gillian911911** [comment]
您好，
在前端请求时，带有默认路径。

报了以下异常，请问您方便指点一下吗？

![ad59a4f45dda8671fefb9ea3bb93bb9](https://user-images.githubusercontent.com/44223931/172901446-6a10b56d-9c93-4138-8045-93bc499f321f.png)

**Comment by gillian911911** [comment]
您好，

首先非常感谢您百忙之中抽空指教。

1. 按照您的建议，上述问题已解决。感谢！
2. 在"/modelEnd/startTraining"接口进行请求时，遇到了异常： file_path 带有默认路径(如下图)。

![image](https://user-images.githubusercontent.com/44223931/172904584-10d51db2-35af-445c-a07a-e4453d354172.png)

![a64686deb393e8baa012a710ef45b02](https://user-images.githubusercontent.com/44223931/172906579-c634aa60-ca7e-4494-bfc0-2ffae9f6dc22.png)

![ad59a4f45dda8671fefb9ea3bb93bb9](https://user-images.githubusercontent.com/44223931/172901446-6a10b56d-9c93-4138-8045-93bc499f321f.png)

请问您方便指点一下吗？


您好，这个问题我经过自己阅读源码已经解决了，issues就先关了，再次感谢 @FlameSky-S @iyuge2  提供的工具和答疑。

我把遇到的问题做了简单汇总，也方便其他人在遇到的时候有所参考 。

1.  cannot import name 'DEMO_run' from 'MMSA' (/root/anaconda3/lib/python3.8/site-packages/MMSA/__init__.py)
 作者已答复，需要 `pip install mysql-connector-python` ，这个依赖在项目的`requirements.txt`中不存在，py的报错有迷惑性。

2.  最新的代码如何执行。
作者已经答复 通过 python main.py 执行

3.  在"/modelEnd/startTraining"接口进行请求时，遇到了异常： file_path 带有默认路径。

startTraining接口请求是会带上/home/xxx的一个路径，经过阅读代码发现，前端会请求一次queryArgs，会把这个路径查出来，。 修改`config_regression.json`和`config_tune.json`文件中的`dataset_root_dir`即可，改成和后端项目的constants.py中配置的dataset_root_dir的路径一致即可。

此问题造成的原因：这个路径是在MMSA项目中的config/下的配置文件中写死的 （MMSA_run方法传递的config_file=""， 这里或许需要改下mmsa_run的代码，在m-sena调用的时候，把配置文件带过来，这样就不用改mmsa的config.json了）不太熟悉py，不清楚在参数列表中 config_file=""，是否会调用传参的时候默认config_file的值都是“”

这里还要注意Windows和Linux文件路径格式的问题，如果是Windows，记得把featurePath的/也换成Windows的\\路径。

**Comment by gillian911911** [comment]
您好，

首先非常感谢您百忙之中抽空指教。

1. 按照您的建议，上述问题已解决。感谢！
2. 在"/modelEnd/startTraining"接口进行请求时，遇到了异常： file_path 带有默认路径(如下图)。

![image](https://user-images.githubusercontent.com/44223931/172904584-10d51db2-35af-445c-a07a-e4453d354172.png)

![a64686deb393e8baa012a710ef45b02](https://user-images.githubusercontent.com/44223931/172906579-c634aa60-ca7e-4494-bfc0-2ffae9f6dc22.png)

![ad59a4f45dda8671fefb9ea3bb93bb9](https://user-images.githubusercontent.com/44223931/172901446-6a10b56d-9c93-4138-8045-93bc499f321f.png)

请问您方便指点一下吗？


您好，这个问题我经过自己阅读源码已经解决了，issues就先关了，再次感谢 @FlameSky-S @iyuge2  提供的工具和答疑。

我把遇到的问题做了简单汇总，也方便其他人在遇到的时候有所参考 。

1.  cannot import name 'DEMO_run' from 'MMSA' (/root/anaconda3/lib/python3.8/site-packages/MMSA/__init__.py)
 作者已答复，需要 `pip install mysql-connector-python` ，这个依赖在项目的`requirements.txt`中不存在，py的报错有迷惑性。

2.  最新的代码如何执行。
作者已经答复 通过 python main.py 执行

3.  在"/modelEnd/startTraining"接口进行请求时，遇到了异常： file_path 带有默认路径。

startTraining接口请求是会带上/home/xxx的一个路径，经过阅读代码发现，前端会请求一次queryArgs，会把这个路径查出来，。 修改`config_regression.json`和`config_tune.json`文件中的`dataset_root_dir`即可，改成和后端项目的constants.py中配置的dataset_root_dir的路径一致即可。

此问题造成的原因：这个路径是在MMSA项目中的config/下的配置文件中写死的 （MMSA_run方法传递的config_file=""， 这里或许需要改下mmsa_run的代码，在m-sena调用的时候，把配置文件带过来，这样就不用改mmsa的config.json了）不太熟悉py，不清楚在参数列表中 config_file=""，是否会调用传参的时候默认config_file的值都是“”

这里还要注意Windows和Linux文件路径格式的问题，如果是Windows，记得把featurePath的/也换成Windows的\\路径。

**Comment by FlameSky-S** [comment]
感谢您对我们工作的关注，后续我们会更新文档以匹配最新版本，路径的问题我们也会进一步完善。感谢您的宝贵意见！

**Comment by IndustryZoe** [comment]
> 

您好，直接python main.py 报错：
“RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
”

**Comment by IndustryZoe** [comment]
> 您好，当前文档是基于之前v_1.0版本的，没有进行更新。对于最新master分支，直接执行`python main.py` 即可。
您好，直接执行python main.py报错：
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

**Comment by IndustryZoe** [comment]
> 感谢您对我们工作的关注，后续我们会更新文档以匹配最新版本，路径的问题我们也会进一步完善。感谢您的宝贵意见！

您好，这可以更新一下代码吗？文本描述与代码不一致，而且少了config.sh
